// SQLQuest: The Buried City — 53 missions across 10 levels

export const sqlMissions = [
  // ─── LEVEL 1: The Surface Layer ────────────────────────────────────────
  {
    id: 'sql-mission-01',
    level: 1,
    command: 'SELECT * FROM artifacts',
    aliases: ['select * from artifacts'],
    narrative: 'You brush sand from the first tablet grid. The asterisk is an ancient symbol meaning everything — you want to see every column, every row, every artifact the city recorded. The full grid illuminates. Overwhelming, but it\'s a start.',
    npcName: 'The Veteran Excavator',
    npcLine: '2,847 rows returned — every artifact in the city\'s record.',
    terminalOutput: [
      'id  | name                | era        | age  | condition | site_id | excavator_id',
      '----|---------------------|------------|------|-----------|---------|-------------',
      '1   | Bronze Dagger       | Bronze Age | 3200 | good      | 1       | 3',
      '2   | Clay Vessel         | Classical  | 1847 | fragmented| 2       | 1',
      '3   | Obsidian Mirror     | Bronze Age | 4100 | pristine  | 1       | 3',
      '... | ...                 | ...        | ...  | ...       | ...     | ...',
      '',
      '(2,847 rows)',
    ],
    terminalOutputError: 'Try: SELECT * FROM artifacts',
    xp: 30,
    unlocksCodex: true,
    codexKey: 'sql-select-star',
    hint: 'Select all columns from a table: SELECT * FROM artifacts',
    stateChange: {},
    specialType: null,
  },
  {
    id: 'sql-mission-02',
    level: 1,
    command: 'SELECT name, age FROM artifacts',
    aliases: ['select name, age from artifacts'],
    narrative: 'Too much data to process. You narrow your lantern beam — you only need the artifact\'s name and its age. The other columns fade into shadow. The same 2,847 artifacts, but only the two facts you care about.',
    npcName: 'The Veteran Excavator',
    npcLine: 'name, age columns returned across all rows.',
    terminalOutput: [
      'name                | age',
      '--------------------|-----',
      'Bronze Dagger       | 3200',
      'Clay Vessel         | 1847',
      'Obsidian Mirror     | 4100',
      'Iron Lance          | 2600',
      'Alabaster Bowl      | 890',
      '...',
      '',
      '(2,847 rows)',
    ],
    terminalOutputError: 'Try: SELECT name, age FROM artifacts',
    xp: 30,
    unlocksCodex: true,
    codexKey: 'sql-select-columns',
    hint: 'List the columns you want: SELECT name, age FROM artifacts',
    stateChange: {},
    specialType: null,
  },
  {
    id: 'sql-mission-03',
    level: 1,
    command: 'SELECT name FROM excavators',
    aliases: ['select name from excavators'],
    narrative: 'A second table lurks beneath the first — the excavators grid, recording every worker who ever dug here. You read just their names. Twenty-three names emerge from the stone.',
    npcName: 'The Veteran Excavator',
    npcLine: '23 excavator names returned.',
    terminalOutput: [
      'name',
      '-------------------',
      'Maris Theron',
      'Dex Calloway',
      'Yuna Park',
      'Silas Ren',
      'Petra Voss',
      '...',
      '',
      '(23 rows)',
    ],
    terminalOutputError: 'Try: SELECT name FROM excavators',
    xp: 30,
    unlocksCodex: false,
    codexKey: 'sql-select-columns',
    hint: 'Query a different table: SELECT name FROM excavators',
    stateChange: {},
    specialType: null,
  },
  {
    id: 'sql-mission-04',
    level: 1,
    command: 'SELECT * FROM sites',
    aliases: ['select * from sites'],
    narrative: 'A third table: excavation sites — grid references, depths, discovery dates. You pull the whole thing. The city is bigger than you imagined.',
    npcName: 'The Veteran Excavator',
    npcLine: '14 active dig sites recorded.',
    terminalOutput: [
      'id  | location | depth_m | discovered     | active',
      '----|----------|---------|----------------|-------',
      '1   | NW-3     | 12      | 2019-03-14     | true',
      '2   | NE-7     | 8       | 2020-06-22     | true',
      '3   | NW-7     | 42      | 2023-11-01     | true',
      '...',
      '',
      '(14 rows)',
    ],
    terminalOutputError: 'Try: SELECT * FROM sites',
    xp: 30,
    unlocksCodex: false,
    codexKey: 'sql-select-star',
    hint: 'Select all from the sites table: SELECT * FROM sites',
    stateChange: {},
    specialType: null,
  },

  // ─── LEVEL 2: The Filter Chamber ───────────────────────────────────────
  {
    id: 'sql-mission-05',
    level: 2,
    command: "SELECT * FROM artifacts WHERE era = 'Bronze Age'",
    aliases: ["select * from artifacts where era = 'bronze age'"],
    narrative: 'Most tablets are irrelevant to your current question. You invoke the WHERE clause — a chisel that chips away everything outside your criteria. Only Bronze Age artifacts survive the filter. The pile shrinks dramatically.',
    npcName: 'The Filter Keeper',
    npcLine: '341 rows returned — Bronze Age artifacts only.',
    terminalOutput: [
      'id  | name            | era        | age  | condition',
      '----|-----------------|------------|------|----------',
      '1   | Bronze Dagger   | Bronze Age | 3200 | good',
      '3   | Obsidian Mirror | Bronze Age | 4100 | pristine',
      '7   | Bronze Seal     | Bronze Age | 2900 | fragmented',
      '...',
      '',
      '(341 rows)',
    ],
    terminalOutputError: "Try: SELECT * FROM artifacts WHERE era = 'Bronze Age'",
    xp: 35,
    unlocksCodex: true,
    codexKey: 'sql-where',
    hint: "Filter rows with WHERE: SELECT * FROM artifacts WHERE era = 'Bronze Age'",
    stateChange: {},
    specialType: null,
  },
  {
    id: 'sql-mission-06',
    level: 2,
    command: 'SELECT * FROM artifacts WHERE age > 3000',
    aliases: ['select * from artifacts where age > 3000'],
    narrative: 'The veteran says the city\'s oldest secrets are in the deepest layers. You filter by age — only artifacts older than 3,000 years. The stone grid thins to its most ancient entries.',
    npcName: 'The Filter Keeper',
    npcLine: '89 rows — artifacts over 3,000 years old.',
    terminalOutput: [
      'id  | name              | era        | age  | condition',
      '----|-------------------|------------|------|----------',
      '3   | Obsidian Mirror   | Bronze Age | 4100 | pristine',
      '9   | Stone Altar       | Neolithic  | 7200 | damaged',
      '14  | Clay Tablet Alpha | Bronze Age | 3400 | good',
      '...',
      '',
      '(89 rows)',
    ],
    terminalOutputError: 'Try: SELECT * FROM artifacts WHERE age > 3000',
    xp: 35,
    unlocksCodex: false,
    codexKey: 'sql-where',
    hint: 'Use a comparison operator: SELECT * FROM artifacts WHERE age > 3000',
    stateChange: {},
    specialType: null,
  },
  {
    id: 'sql-mission-07',
    level: 2,
    command: "SELECT * FROM artifacts WHERE era = 'Bronze Age' AND age > 3000",
    aliases: ["select * from artifacts where era = 'bronze age' and age > 3000"],
    narrative: 'You need both conditions true simultaneously. AND is a double-lock — Bronze Age and ancient. The intersection is small and precious.',
    npcName: 'The Filter Keeper',
    npcLine: '12 rows — old Bronze Age artifacts specifically.',
    terminalOutput: [
      'id  | name              | era        | age  | condition',
      '----|-------------------|------------|------|----------',
      '3   | Obsidian Mirror   | Bronze Age | 4100 | pristine',
      '14  | Clay Tablet Alpha | Bronze Age | 3400 | good',
      '22  | Bronze Idol       | Bronze Age | 3800 | damaged',
      '...',
      '',
      '(12 rows)',
    ],
    terminalOutputError: "Try: SELECT * FROM artifacts WHERE era = 'Bronze Age' AND age > 3000",
    xp: 40,
    unlocksCodex: true,
    codexKey: 'sql-and-or',
    hint: "Combine conditions with AND: WHERE era = 'Bronze Age' AND age > 3000",
    stateChange: {},
    specialType: null,
  },
  {
    id: 'sql-mission-08',
    level: 2,
    command: "SELECT * FROM artifacts WHERE era = 'Bronze Age' OR era = 'Iron Age'",
    aliases: ["select * from artifacts where era = 'bronze age' or era = 'iron age'"],
    narrative: 'A rival theory emerges — the secret could be in either era. OR broadens your net: Bronze Age or Iron Age, either will do. The pile grows back.',
    npcName: 'The Filter Keeper',
    npcLine: '598 rows — Bronze and Iron Age combined.',
    terminalOutput: [
      '(598 rows — Bronze Age and Iron Age artifacts)',
    ],
    terminalOutputError: "Try: SELECT * FROM artifacts WHERE era = 'Bronze Age' OR era = 'Iron Age'",
    xp: 35,
    unlocksCodex: false,
    codexKey: 'sql-and-or',
    hint: "Use OR to match either condition: WHERE era = 'Bronze Age' OR era = 'Iron Age'",
    stateChange: {},
    specialType: null,
  },
  {
    id: 'sql-mission-09',
    level: 2,
    command: "SELECT * FROM artifacts WHERE NOT era = 'Modern'",
    aliases: ["select * from artifacts where not era = 'modern'", "select * from artifacts where era != 'modern'", "select * from artifacts where era <> 'modern'"],
    narrative: 'Modern replicas contaminate the site — tourists, fraudsters, previous careless diggers. You exclude everything Modern. NOT inverts the filter like flipping a tablet face-down.',
    npcName: 'The Filter Keeper',
    npcLine: '2,701 rows — all non-modern artifacts.',
    terminalOutput: [
      '(2,701 rows — all artifacts except Modern era)',
    ],
    terminalOutputError: "Try: SELECT * FROM artifacts WHERE NOT era = 'Modern'",
    xp: 35,
    unlocksCodex: true,
    codexKey: 'sql-not',
    hint: "Negate a condition with NOT: WHERE NOT era = 'Modern'",
    stateChange: {},
    specialType: null,
  },
  {
    id: 'sql-mission-10',
    level: 2,
    command: "SELECT * FROM artifacts WHERE name LIKE 'Obsidian%'",
    aliases: ["select * from artifacts where name like 'obsidian%'"],
    narrative: 'You vaguely remember an artifact starting with "Obsidian" but can\'t recall the full name. You carve a partial pattern into your chisel — the % wildcard matches anything that follows.',
    npcName: 'The Filter Keeper',
    npcLine: '3 rows — all artifacts with names starting \'Obsidian\'.',
    terminalOutput: [
      'name',
      '----------------',
      'Obsidian Idol',
      'Obsidian Blade',
      'Obsidian Mirror',
      '',
      '(3 rows)',
    ],
    terminalOutputError: "Try: SELECT * FROM artifacts WHERE name LIKE 'Obsidian%'",
    xp: 40,
    unlocksCodex: true,
    codexKey: 'sql-like',
    hint: "Pattern match with LIKE and %: WHERE name LIKE 'Obsidian%'",
    stateChange: {},
    specialType: null,
  },
  {
    id: 'sql-mission-11',
    level: 2,
    command: 'SELECT * FROM artifacts WHERE age BETWEEN 2000 AND 4000',
    aliases: ['select * from artifacts where age between 2000 and 4000'],
    narrative: 'The veteran theorizes the critical period was between 2,000 and 4,000 years ago. Rather than writing out two conditions, you use a single elegant range filter. Both endpoints are included.',
    npcName: 'The Filter Keeper',
    npcLine: '1,142 rows — artifacts from the critical period.',
    terminalOutput: [
      '(1,142 rows — artifacts between 2,000 and 4,000 years old)',
    ],
    terminalOutputError: 'Try: SELECT * FROM artifacts WHERE age BETWEEN 2000 AND 4000',
    xp: 40,
    unlocksCodex: true,
    codexKey: 'sql-between',
    hint: 'Use BETWEEN for ranges: WHERE age BETWEEN 2000 AND 4000',
    stateChange: {},
    specialType: null,
  },
  {
    id: 'sql-mission-12',
    level: 2,
    command: "SELECT * FROM artifacts WHERE era = 'Bronze Age' AND (age > 3000 OR condition = 'pristine')",
    aliases: ["select * from artifacts where era = 'bronze age' and (age > 3000 or condition = 'pristine')"],
    narrative: 'The mystery deepens. You need Bronze Age artifacts that are either ancient or in perfect condition — parentheses group the logic like brackets around a subclause of truth. The city rewards precision.',
    npcName: 'The Filter Keeper',
    npcLine: '47 rows — the refined target set.',
    terminalOutput: [
      '(47 rows — Bronze Age: ancient OR pristine)',
    ],
    terminalOutputError: "Try: SELECT * FROM artifacts WHERE era = 'Bronze Age' AND (age > 3000 OR condition = 'pristine')",
    xp: 45,
    unlocksCodex: false,
    codexKey: 'sql-and-or',
    hint: "Use parentheses to group OR conditions: AND (age > 3000 OR condition = 'pristine')",
    stateChange: {},
    specialType: null,
  },

  // ─── LEVEL 3: The Sorting Hall ──────────────────────────────────────────
  {
    id: 'sql-mission-13',
    level: 3,
    command: 'SELECT name, age FROM artifacts ORDER BY age',
    aliases: ['select name, age from artifacts order by age'],
    narrative: 'The cataloguing hall is chaos — tablets stacked randomly. ORDER BY is the sorting ritual. You arrange artifacts youngest to oldest. The hall reorganizes itself before your eyes, ascending.',
    npcName: 'The Cataloguer',
    npcLine: '2,847 rows — sorted youngest to oldest.',
    terminalOutput: [
      'name                | age',
      '--------------------|-----',
      'Modern Replica      | 12',
      'Tourist Token       | 35',
      'Recent Carving      | 87',
      '...',
      'Stone Altar         | 7200',
      'Ancient Figurine    | 9247',
      '',
      '(2,847 rows, sorted ASC)',
    ],
    terminalOutputError: 'Try: SELECT name, age FROM artifacts ORDER BY age',
    xp: 35,
    unlocksCodex: true,
    codexKey: 'sql-order-by',
    hint: 'Sort results with ORDER BY: SELECT name, age FROM artifacts ORDER BY age',
    stateChange: {},
    specialType: null,
  },
  {
    id: 'sql-mission-14',
    level: 3,
    command: 'SELECT name, age FROM artifacts ORDER BY age DESC',
    aliases: ['select name, age from artifacts order by age desc'],
    narrative: 'Flip it. You want the oldest first — the deepest history at the top. DESC reverses the order. The most ancient artifacts rise to the surface.',
    npcName: 'The Cataloguer',
    npcLine: 'Sorted oldest first — a 9,200-year-old idol tops the list.',
    terminalOutput: [
      'name                | age',
      '--------------------|-----',
      'Ancient Figurine    | 9247',
      'Stone Altar         | 7200',
      'Neolithic Vessel    | 6800',
      '...',
      '',
      '(2,847 rows, sorted DESC)',
    ],
    terminalOutputError: 'Try: SELECT name, age FROM artifacts ORDER BY age DESC',
    xp: 35,
    unlocksCodex: false,
    codexKey: 'sql-order-by',
    hint: 'Reverse sort order with DESC: ORDER BY age DESC',
    stateChange: {},
    specialType: null,
  },
  {
    id: 'sql-mission-15',
    level: 3,
    command: 'SELECT name, age FROM artifacts ORDER BY era, age DESC',
    aliases: ['select name, age from artifacts order by era, age desc'],
    narrative: 'Two sort keys — first group by era alphabetically, then within each era sort oldest first. The hall reorganizes in layers, like geological strata.',
    npcName: 'The Cataloguer',
    npcLine: 'Multi-column sort applied — era groups, age descending within.',
    terminalOutput: [
      'name                | age  | (era: sorted A→Z, age: oldest first within each)',
      '--------------------|------|---',
      'Bronze Idol         | 4100 | (Bronze Age)',
      'Clay Tablet Alpha   | 3400 | (Bronze Age)',
      '...',
      'Iron Sword          | 2600 | (Iron Age)',
      '...',
      '',
      '(2,847 rows)',
    ],
    terminalOutputError: 'Try: SELECT name, age FROM artifacts ORDER BY era, age DESC',
    xp: 40,
    unlocksCodex: true,
    codexKey: 'sql-order-by',
    hint: 'Multi-column sort: ORDER BY era, age DESC',
    stateChange: {},
    specialType: null,
  },
  {
    id: 'sql-mission-16',
    level: 3,
    command: 'SELECT * FROM artifacts LIMIT 10',
    aliases: ['select * from artifacts limit 10'],
    narrative: 'You can\'t study all 2,847 at once. LIMIT is a physical constraint — you pull only the first ten tablets from the stack. Manageable. Focused.',
    npcName: 'The Cataloguer',
    npcLine: '10 rows returned — first page of results.',
    terminalOutput: [
      '(10 rows — first page of artifacts)',
    ],
    terminalOutputError: 'Try: SELECT * FROM artifacts LIMIT 10',
    xp: 30,
    unlocksCodex: true,
    codexKey: 'sql-limit',
    hint: 'Cap results with LIMIT: SELECT * FROM artifacts LIMIT 10',
    stateChange: {},
    specialType: null,
  },
  {
    id: 'sql-mission-17',
    level: 3,
    command: 'SELECT * FROM artifacts LIMIT 10 OFFSET 10',
    aliases: ['select * from artifacts limit 10 offset 10'],
    narrative: 'You\'ve studied the first ten. Now the next ten. OFFSET skips the ones you\'ve already read, like lifting the first stack off the pile before grabbing the second. Pagination, archaeologically speaking.',
    npcName: 'The Cataloguer',
    npcLine: 'Rows 11–20 returned.',
    terminalOutput: [
      '(Rows 11–20 — second page of results)',
    ],
    terminalOutputError: 'Try: SELECT * FROM artifacts LIMIT 10 OFFSET 10',
    xp: 35,
    unlocksCodex: true,
    codexKey: 'sql-limit',
    hint: 'Skip rows with OFFSET: LIMIT 10 OFFSET 10',
    stateChange: {},
    specialType: null,
  },
  {
    id: 'sql-mission-18',
    level: 3,
    command: 'SELECT a.name, a.age, s.location FROM artifacts AS a JOIN sites AS s ON a.site_id = s.id',
    aliases: [
      'select a.name, a.age, s.location from artifacts as a join sites as s on a.site_id = s.id',
      'select a.name, a.age, s.location from artifacts a join sites s on a.site_id = s.id',
    ],
    narrative: 'The veteran introduces shorthand. "Writing artifacts.name every time is tedious. Give each table a short alias." You assign a for artifacts and s for sites. The query reads cleaner; the results are identical.',
    npcName: 'The Cataloguer',
    npcLine: 'Table aliases applied — same results, cleaner syntax.',
    terminalOutput: [
      'name              | age  | location',
      '------------------|------|----------',
      'Bronze Dagger     | 3200 | NW-3',
      'Clay Vessel       | 1847 | NE-7',
      'Obsidian Mirror   | 4100 | NW-3',
      '...',
      '',
      '(2,847 rows)',
    ],
    terminalOutputError: 'Try: SELECT a.name, a.age, s.location FROM artifacts AS a JOIN sites AS s ON a.site_id = s.id',
    xp: 45,
    unlocksCodex: true,
    codexKey: 'sql-aliases',
    hint: 'Alias tables with AS: FROM artifacts AS a JOIN sites AS s ON a.site_id = s.id',
    stateChange: {},
    specialType: null,
  },

  // ─── LEVEL 4: The Measurement Vaults ────────────────────────────────────
  {
    id: 'sql-mission-19',
    level: 4,
    command: 'SELECT COUNT(*) FROM artifacts',
    aliases: ['select count(*) from artifacts'],
    narrative: 'How many artifacts exist in total? COUNT collapses the entire grid into a single number. The city\'s statisticians did this constantly — a census of objects.',
    npcName: 'The Accountant',
    npcLine: '2,847',
    terminalOutput: [
      'COUNT(*)',
      '--------',
      '2847',
    ],
    terminalOutputError: 'Try: SELECT COUNT(*) FROM artifacts',
    xp: 35,
    unlocksCodex: true,
    codexKey: 'sql-count',
    hint: 'Count all rows: SELECT COUNT(*) FROM artifacts',
    stateChange: {},
    specialType: null,
  },
  {
    id: 'sql-mission-20',
    level: 4,
    command: "SELECT COUNT(*) FROM artifacts WHERE era = 'Bronze Age'",
    aliases: ["select count(*) from artifacts where era = 'bronze age'"],
    narrative: 'A targeted census — how many Bronze Age artifacts specifically? COUNT pairs with WHERE like a lantern with a filter lens.',
    npcName: 'The Accountant',
    npcLine: '341',
    terminalOutput: [
      'COUNT(*)',
      '--------',
      '341',
    ],
    terminalOutputError: "Try: SELECT COUNT(*) FROM artifacts WHERE era = 'Bronze Age'",
    xp: 35,
    unlocksCodex: false,
    codexKey: 'sql-count',
    hint: "Count filtered rows: SELECT COUNT(*) FROM artifacts WHERE era = 'Bronze Age'",
    stateChange: {},
    specialType: null,
  },
  {
    id: 'sql-mission-21',
    level: 4,
    command: 'SELECT AVG(age) FROM artifacts',
    aliases: ['select avg(age) from artifacts'],
    narrative: 'What\'s the average age of an artifact in Queryra? AVG adds every age and divides. The city\'s median history emerges as a number.',
    npcName: 'The Accountant',
    npcLine: '1,847 years — the average artifact age.',
    terminalOutput: [
      'AVG(age)',
      '--------',
      '1847.3',
    ],
    terminalOutputError: 'Try: SELECT AVG(age) FROM artifacts',
    xp: 35,
    unlocksCodex: true,
    codexKey: 'sql-aggregate',
    hint: 'Calculate average: SELECT AVG(age) FROM artifacts',
    stateChange: {},
    specialType: null,
  },
  {
    id: 'sql-mission-22',
    level: 4,
    command: 'SELECT MIN(age), MAX(age) FROM artifacts',
    aliases: ['select min(age), max(age) from artifacts'],
    narrative: 'Two extremes at once — the youngest and the oldest artifact in the record. MIN and MAX are the city\'s bookends.',
    npcName: 'The Accountant',
    npcLine: 'MIN: 12 years / MAX: 9,247 years',
    terminalOutput: [
      'MIN(age) | MAX(age)',
      '---------|--------',
      '12       | 9247',
    ],
    terminalOutputError: 'Try: SELECT MIN(age), MAX(age) FROM artifacts',
    xp: 35,
    unlocksCodex: false,
    codexKey: 'sql-aggregate',
    hint: 'Get min and max: SELECT MIN(age), MAX(age) FROM artifacts',
    stateChange: {},
    specialType: null,
  },
  {
    id: 'sql-mission-23',
    level: 4,
    command: "SELECT SUM(estimated_value) FROM artifacts WHERE condition = 'pristine'",
    aliases: ["select sum(estimated_value) from artifacts where condition = 'pristine'"],
    narrative: 'The expedition accountant needs a budget figure — total estimated value of all pristine artifacts. SUM collapses a column into its total. A staggering number appears.',
    npcName: 'The Accountant',
    npcLine: '$4,283,900 — total pristine artifact value.',
    terminalOutput: [
      'SUM(estimated_value)',
      '--------------------',
      '4283900',
    ],
    terminalOutputError: "Try: SELECT SUM(estimated_value) FROM artifacts WHERE condition = 'pristine'",
    xp: 40,
    unlocksCodex: true,
    codexKey: 'sql-aggregate',
    hint: "Sum a column: SELECT SUM(estimated_value) FROM artifacts WHERE condition = 'pristine'",
    stateChange: {},
    specialType: null,
  },

  // ─── LEVEL 5: The Guild Records ─────────────────────────────────────────
  {
    id: 'sql-mission-24',
    level: 5,
    command: 'SELECT era, COUNT(*) FROM artifacts GROUP BY era',
    aliases: ['select era, count(*) from artifacts group by era'],
    narrative: 'You want a breakdown — how many artifacts per era? GROUP BY splits the table into clusters, one per unique era value, and COUNT tallies each cluster.',
    npcName: 'The Guild Archivist',
    npcLine: 'Bronze Age: 341 / Iron Age: 257 / Classical: 891 / Modern: 146...',
    terminalOutput: [
      'era          | COUNT(*)',
      '-------------|--------',
      'Bronze Age   | 341',
      'Iron Age     | 257',
      'Classical    | 891',
      'Hellenistic  | 423',
      'Late Period  | 789',
      'Modern       | 146',
      '',
      '(8 rows)',
    ],
    terminalOutputError: 'Try: SELECT era, COUNT(*) FROM artifacts GROUP BY era',
    xp: 45,
    unlocksCodex: true,
    codexKey: 'sql-group-by',
    hint: 'Group and count: SELECT era, COUNT(*) FROM artifacts GROUP BY era',
    stateChange: {},
    specialType: null,
  },
  {
    id: 'sql-mission-25',
    level: 5,
    command: 'SELECT era, AVG(age) FROM artifacts GROUP BY era',
    aliases: ['select era, avg(age) from artifacts group by era'],
    narrative: 'Same grouping, different question — what\'s the average age of artifacts within each era? AVG now works inside each group rather than across the whole table.',
    npcName: 'The Guild Archivist',
    npcLine: 'Bronze Age avg: 2,847 years / Iron Age avg: 2,103 years...',
    terminalOutput: [
      'era          | AVG(age)',
      '-------------|--------',
      'Bronze Age   | 2847.1',
      'Iron Age     | 2103.4',
      'Classical    | 1421.8',
      '...',
    ],
    terminalOutputError: 'Try: SELECT era, AVG(age) FROM artifacts GROUP BY era',
    xp: 40,
    unlocksCodex: false,
    codexKey: 'sql-group-by',
    hint: 'Aggregate within groups: SELECT era, AVG(age) FROM artifacts GROUP BY era',
    stateChange: {},
    specialType: null,
  },
  {
    id: 'sql-mission-26',
    level: 5,
    command: 'SELECT excavator_id, COUNT(*) FROM artifacts GROUP BY excavator_id',
    aliases: ['select excavator_id, count(*) from artifacts group by excavator_id'],
    narrative: 'The veteran suspects some excavators are hoarding finds. You group by excavator and count their attributed artifacts. A suspicious outlier emerges — one excavator has attributed 847 artifacts to themselves.',
    npcName: 'The Guild Archivist',
    npcLine: 'excavator_id 7: 847 artifacts — statistical anomaly.',
    terminalOutput: [
      'excavator_id | COUNT(*)',
      '-------------|--------',
      '1            | 124',
      '2            | 89',
      '3            | 201',
      '7            | 847',
      '...',
      '',
      '(23 rows)',
    ],
    terminalOutputError: 'Try: SELECT excavator_id, COUNT(*) FROM artifacts GROUP BY excavator_id',
    xp: 40,
    unlocksCodex: false,
    codexKey: 'sql-group-by',
    hint: 'Group by a foreign key: SELECT excavator_id, COUNT(*) FROM artifacts GROUP BY excavator_id',
    stateChange: {},
    specialType: null,
  },
  {
    id: 'sql-mission-27',
    level: 5,
    command: 'SELECT era, COUNT(*) FROM artifacts GROUP BY era HAVING COUNT(*) > 200',
    aliases: ['select era, count(*) from artifacts group by era having count(*) > 200'],
    narrative: 'You only care about eras with significant representation — minor eras with a handful of artifacts are noise. HAVING filters after grouping, the way WHERE filters before. Only eras with more than 200 artifacts survive.',
    npcName: 'The Guild Archivist',
    npcLine: '3 eras returned — Bronze Age, Classical, and Late Period.',
    terminalOutput: [
      'era          | COUNT(*)',
      '-------------|--------',
      'Bronze Age   | 341',
      'Classical    | 891',
      'Late Period  | 789',
      '',
      '(3 rows)',
    ],
    terminalOutputError: 'Try: SELECT era, COUNT(*) FROM artifacts GROUP BY era HAVING COUNT(*) > 200',
    xp: 50,
    unlocksCodex: true,
    codexKey: 'sql-having',
    hint: 'Filter groups with HAVING: GROUP BY era HAVING COUNT(*) > 200',
    stateChange: {},
    specialType: null,
  },
  {
    id: 'sql-mission-28',
    level: 5,
    command: 'SELECT excavator_id, COUNT(*) FROM artifacts GROUP BY excavator_id HAVING COUNT(*) > 100',
    aliases: ['select excavator_id, count(*) from artifacts group by excavator_id having count(*) > 100'],
    narrative: 'Back to the suspicious excavator. You filter to only those with over 100 attributed finds. Three names remain — but excavator 7 is far ahead of the others. The investigation deepens.',
    npcName: 'The Guild Archivist',
    npcLine: '3 excavators with >100 finds — ID 7 is an outlier.',
    terminalOutput: [
      'excavator_id | COUNT(*)',
      '-------------|--------',
      '3            | 201',
      '7            | 847',
      '12           | 134',
      '',
      '(3 rows)',
    ],
    terminalOutputError: 'Try: SELECT excavator_id, COUNT(*) FROM artifacts GROUP BY excavator_id HAVING COUNT(*) > 100',
    xp: 45,
    unlocksCodex: false,
    codexKey: 'sql-having',
    hint: 'Filter groups: GROUP BY excavator_id HAVING COUNT(*) > 100',
    stateChange: {},
    specialType: null,
  },

  // ─── LEVEL 6: The Connection Bridges ────────────────────────────────────
  {
    id: 'sql-mission-29',
    level: 6,
    command: 'SELECT a.name, e.name FROM artifacts a JOIN excavators e ON a.excavator_id = e.id',
    aliases: [
      'select a.name, e.name from artifacts a join excavators e on a.excavator_id = e.id',
      'select a.name, e.name from artifacts a inner join excavators e on a.excavator_id = e.id',
    ],
    narrative: 'The artifact records only contain an excavator ID number — not a name. The excavator table has the names. JOIN bridges the two tables on the shared key. Now every artifact row carries its excavator\'s actual name.',
    npcName: 'The Bridge Builder',
    npcLine: '2,847 rows — artifact name paired with excavator name.',
    terminalOutput: [
      'a.name            | e.name',
      '------------------|-------------------',
      'Bronze Dagger     | Petra Voss',
      'Clay Vessel       | Dex Calloway',
      'Obsidian Mirror   | Petra Voss',
      '...',
      '',
      '(2,847 rows)',
    ],
    terminalOutputError: 'Try: SELECT a.name, e.name FROM artifacts a JOIN excavators e ON a.excavator_id = e.id',
    xp: 55,
    unlocksCodex: true,
    codexKey: 'sql-join',
    hint: 'Connect tables with JOIN: FROM artifacts a JOIN excavators e ON a.excavator_id = e.id',
    stateChange: {},
    specialType: null,
  },
  {
    id: 'sql-mission-30',
    level: 6,
    command: 'SELECT a.name, s.location FROM artifacts a JOIN sites s ON a.site_id = s.id',
    aliases: ['select a.name, s.location from artifacts a join sites s on a.site_id = s.id'],
    narrative: 'A third building holds site location records. You bridge artifacts to sites — now every artifact knows exactly where it was physically found. Geography enters the record.',
    npcName: 'The Bridge Builder',
    npcLine: 'Artifact names paired with dig site coordinates.',
    terminalOutput: [
      'a.name            | s.location',
      '------------------|----------',
      'Bronze Dagger     | NW-3',
      'Clay Vessel       | NE-7',
      'Obsidian Mirror   | NW-3',
      '...',
      '',
      '(2,847 rows)',
    ],
    terminalOutputError: 'Try: SELECT a.name, s.location FROM artifacts a JOIN sites s ON a.site_id = s.id',
    xp: 45,
    unlocksCodex: false,
    codexKey: 'sql-join',
    hint: 'Join artifacts to sites: FROM artifacts a JOIN sites s ON a.site_id = s.id',
    stateChange: {},
    specialType: null,
  },
  {
    id: 'sql-mission-31',
    level: 6,
    command: 'SELECT a.name, e.name AS excavator, s.location FROM artifacts a JOIN excavators e ON a.excavator_id = e.id JOIN sites s ON a.site_id = s.id',
    aliases: ['select a.name, e.name as excavator, s.location from artifacts a join excavators e on a.excavator_id = e.id join sites s on a.site_id = s.id'],
    narrative: 'A double bridge — three buildings connected in sequence. Every artifact row now carries who found it and where. The city\'s full provenance chain emerges.',
    npcName: 'The Bridge Builder',
    npcLine: 'Three-table join — full artifact provenance returned.',
    terminalOutput: [
      'a.name          | excavator    | s.location',
      '----------------|--------------|----------',
      'Bronze Dagger   | Petra Voss   | NW-3',
      'Clay Vessel     | Dex Calloway | NE-7',
      '...',
      '',
      '(2,847 rows)',
    ],
    terminalOutputError: 'Try: SELECT a.name, e.name AS excavator, s.location FROM artifacts a JOIN excavators e ON a.excavator_id = e.id JOIN sites s ON a.site_id = s.id',
    xp: 55,
    unlocksCodex: true,
    codexKey: 'sql-join',
    hint: 'Chain multiple JOINs: JOIN excavators e ON ... JOIN sites s ON ...',
    stateChange: {},
    specialType: null,
  },
  {
    id: 'sql-mission-32',
    level: 6,
    command: "SELECT a.name, e.name AS excavator FROM artifacts a JOIN excavators e ON a.excavator_id = e.id WHERE e.name = 'Maris Theron'",
    aliases: ["select a.name, e.name as excavator from artifacts a join excavators e on a.excavator_id = e.id where e.name = 'maris theron'"],
    narrative: 'You\'ve identified the suspicious excavator by name: Maris Theron. You bridge the tables and filter immediately — every artifact attributed to her, with her name confirmed from the excavator record.',
    npcName: 'The Bridge Builder',
    npcLine: '847 rows — all Maris Theron\'s attributed finds.',
    terminalOutput: [
      'a.name              | excavator',
      '--------------------|-------------',
      'Bronze Dagger       | Maris Theron',
      'Gold Signet Ring    | Maris Theron',
      '...',
      '',
      '(847 rows)',
    ],
    terminalOutputError: "Try: SELECT a.name, e.name AS excavator FROM artifacts a JOIN excavators e ON a.excavator_id = e.id WHERE e.name = 'Maris Theron'",
    xp: 50,
    unlocksCodex: false,
    codexKey: 'sql-join',
    hint: "Add WHERE after JOIN: WHERE e.name = 'Maris Theron'",
    stateChange: {},
    specialType: null,
  },

  // ─── LEVEL 7: The Outer Archives ────────────────────────────────────────
  {
    id: 'sql-mission-33',
    level: 7,
    command: 'SELECT e.name, a.name AS artifact FROM excavators e LEFT JOIN artifacts a ON e.id = a.excavator_id',
    aliases: ['select e.name, a.name as artifact from excavators e left join artifacts a on e.id = a.excavator_id'],
    narrative: 'You want every excavator — even those who found nothing. INNER JOIN would silently drop them. LEFT JOIN keeps all rows from the left table and fills artifact columns with NULL where no match exists.',
    npcName: 'The Outer Archivist',
    npcLine: '2,850+ rows — including 3 excavators paired with NULL artifact names.',
    terminalOutput: [
      'e.name         | artifact',
      '---------------|------------------',
      'Maris Theron   | Bronze Dagger',
      'Maris Theron   | Gold Signet Ring',
      'Yuna Park      | NULL',
      'Silas Ren      | NULL',
      'Lena Marsh     | NULL',
      '...',
    ],
    terminalOutputError: 'Try: SELECT e.name, a.name AS artifact FROM excavators e LEFT JOIN artifacts a ON e.id = a.excavator_id',
    xp: 55,
    unlocksCodex: true,
    codexKey: 'sql-left-join',
    hint: 'Keep all left table rows: FROM excavators e LEFT JOIN artifacts a ON ...',
    stateChange: {},
    specialType: null,
  },
  {
    id: 'sql-mission-34',
    level: 7,
    command: 'SELECT e.name, COUNT(a.id) AS find_count FROM excavators e LEFT JOIN artifacts a ON e.id = a.excavator_id GROUP BY e.name',
    aliases: ['select e.name, count(a.id) as find_count from excavators e left join artifacts a on e.id = a.excavator_id group by e.name'],
    narrative: 'A productivity report — every excavator and their find count, including the zeroes. LEFT JOIN plus GROUP BY plus COUNT gives you the full picture, no silent omissions.',
    npcName: 'The Outer Archivist',
    npcLine: '23 excavators with counts — 3 show 0.',
    terminalOutput: [
      'e.name         | find_count',
      '---------------|----------',
      'Maris Theron   | 847',
      'Petra Voss     | 201',
      'Dex Calloway   | 124',
      'Yuna Park      | 0',
      'Silas Ren      | 0',
      'Lena Marsh     | 0',
      '...',
      '',
      '(23 rows)',
    ],
    terminalOutputError: 'Try: SELECT e.name, COUNT(a.id) AS find_count FROM excavators e LEFT JOIN artifacts a ON e.id = a.excavator_id GROUP BY e.name',
    xp: 55,
    unlocksCodex: false,
    codexKey: 'sql-left-join',
    hint: 'COUNT(a.id) counts non-NULL values — excavators with no finds get 0',
    stateChange: {},
    specialType: null,
  },
  {
    id: 'sql-mission-35',
    level: 7,
    command: 'SELECT * FROM artifacts WHERE excavator_id IS NULL',
    aliases: ['select * from artifacts where excavator_id is null'],
    narrative: 'Some artifacts have no excavator attribution at all — found but unclaimed, or records lost. IS NULL targets the gaps in the record. Seven artifacts exist in a provenance void.',
    npcName: 'The Outer Archivist',
    npcLine: '7 artifacts with no excavator attribution.',
    terminalOutput: [
      'id   | name              | era        | age  | excavator_id',
      '-----|-------------------|------------|------|-------------',
      '144  | Unmarked Tablet   | Unknown    | 4400 | NULL',
      '287  | Faceless Idol     | Bronze Age | 3100 | NULL',
      '...',
      '',
      '(7 rows)',
    ],
    terminalOutputError: 'Try: SELECT * FROM artifacts WHERE excavator_id IS NULL',
    xp: 40,
    unlocksCodex: true,
    codexKey: 'sql-null',
    hint: 'Find missing values: WHERE excavator_id IS NULL',
    stateChange: {},
    specialType: null,
  },
  {
    id: 'sql-mission-36',
    level: 7,
    command: 'SELECT * FROM artifacts WHERE condition IS NOT NULL',
    aliases: ['select * from artifacts where condition is not null'],
    narrative: 'You want only artifacts where condition was actually assessed — IS NOT NULL filters out the unexamined ones.',
    npcName: 'The Outer Archivist',
    npcLine: '2,831 rows — artifacts with condition recorded.',
    terminalOutput: [
      '(2,831 rows — artifacts where condition is recorded)',
    ],
    terminalOutputError: 'Try: SELECT * FROM artifacts WHERE condition IS NOT NULL',
    xp: 35,
    unlocksCodex: false,
    codexKey: 'sql-null',
    hint: 'Exclude missing values: WHERE condition IS NOT NULL',
    stateChange: {},
    specialType: null,
  },

  // ─── LEVEL 8: The Inscription Workshop ──────────────────────────────────
  {
    id: 'sql-mission-37',
    level: 8,
    command: "INSERT INTO artifacts (name, era, age, condition) VALUES ('Obsidian Idol', 'Bronze Age', 3200, 'pristine')",
    aliases: ["insert into artifacts (name, era, age, condition) values ('obsidian idol', 'bronze age', 3200, 'pristine')"],
    narrative: 'A new discovery — a stunning obsidian idol pulled from the deep trench this morning. The city\'s record must grow. INSERT carves a new row into the tablet grid. The artifact officially exists now.',
    npcName: 'The Head Scribe',
    npcLine: '1 row inserted — Obsidian Idol added to record.',
    terminalOutput: [
      'INSERT 0 1',
      '✓ Obsidian Idol added to artifacts table.',
    ],
    terminalOutputError: "Try: INSERT INTO artifacts (name, era, age, condition) VALUES ('Obsidian Idol', 'Bronze Age', 3200, 'pristine')",
    xp: 50,
    unlocksCodex: true,
    codexKey: 'sql-insert',
    hint: "Insert a new row: INSERT INTO artifacts (name, era, age, condition) VALUES ('Obsidian Idol', 'Bronze Age', 3200, 'pristine')",
    stateChange: { mutates: true },
    specialType: null,
  },
  {
    id: 'sql-mission-38',
    level: 8,
    command: "INSERT INTO artifacts (name, era, age, condition, excavator_id) VALUES ('Clay Seal', 'Iron Age', 2100, 'fragmented', 7)",
    aliases: ["insert into artifacts (name, era, age, condition, excavator_id) values ('clay seal', 'iron age', 2100, 'fragmented', 7)"],
    narrative: 'Another find, this one attributed to Maris Theron — excavator ID 7. You note the attribution but flag it for review. The record accepts the row without judgment.',
    npcName: 'The Head Scribe',
    npcLine: '1 row inserted — Clay Seal attributed to ID 7.',
    terminalOutput: [
      'INSERT 0 1',
      '✓ Clay Seal added (attributed to excavator_id 7).',
    ],
    terminalOutputError: "Try: INSERT INTO artifacts (name, era, age, condition, excavator_id) VALUES ('Clay Seal', 'Iron Age', 2100, 'fragmented', 7)",
    xp: 45,
    unlocksCodex: false,
    codexKey: 'sql-insert',
    hint: "Include excavator_id in the INSERT: VALUES ('Clay Seal', 'Iron Age', 2100, 'fragmented', 7)",
    stateChange: { mutates: true },
    specialType: null,
  },
  {
    id: 'sql-mission-39',
    level: 8,
    command: "UPDATE artifacts SET condition = 'restored' WHERE name = 'Obsidian Idol'",
    aliases: ["update artifacts set condition = 'restored' where name = 'obsidian idol'"],
    narrative: 'The conservator has finished restoring the idol. Its condition in the record is outdated. UPDATE reaches into that specific row and rewrites the condition column. The idol\'s entry now reflects reality.',
    npcName: 'The Head Scribe',
    npcLine: '1 row updated — Obsidian Idol condition set to \'restored\'.',
    terminalOutput: [
      'UPDATE 1',
      "✓ Obsidian Idol: condition → 'restored'",
    ],
    terminalOutputError: "Try: UPDATE artifacts SET condition = 'restored' WHERE name = 'Obsidian Idol'",
    xp: 50,
    unlocksCodex: true,
    codexKey: 'sql-update',
    hint: "Update a specific row: UPDATE artifacts SET condition = 'restored' WHERE name = 'Obsidian Idol'",
    stateChange: { mutates: true },
    specialType: null,
  },
  {
    id: 'sql-mission-40',
    level: 8,
    command: "UPDATE artifacts SET excavator_id = 12 WHERE excavator_id = 7 AND era = 'Bronze Age'",
    aliases: ["update artifacts set excavator_id = 12 where excavator_id = 7 and era = 'bronze age'"],
    narrative: 'The investigation concludes — Maris Theron falsely claimed credit for all Bronze Age finds. The real excavator is ID 12. A targeted UPDATE reassigns them. Without the WHERE clause, every artifact in the database would be reassigned. Precision is everything.',
    npcName: 'The Head Scribe',
    npcLine: '127 rows updated — Bronze Age finds reassigned to ID 12.',
    terminalOutput: [
      'UPDATE 127',
      '✓ 127 Bronze Age artifacts reassigned from ID 7 → ID 12.',
    ],
    terminalOutputError: "Try: UPDATE artifacts SET excavator_id = 12 WHERE excavator_id = 7 AND era = 'Bronze Age'",
    xp: 55,
    unlocksCodex: false,
    codexKey: 'sql-update',
    hint: "Update multiple rows carefully: WHERE excavator_id = 7 AND era = 'Bronze Age'",
    stateChange: { mutates: true },
    specialType: null,
  },
  {
    id: 'sql-mission-41',
    level: 8,
    command: "DELETE FROM artifacts WHERE condition = 'counterfeit'",
    aliases: ["delete from artifacts where condition = 'counterfeit'"],
    narrative: 'Lab results confirm eleven artifacts are modern counterfeits planted to inflate the site\'s value — a fraud. They must be purged from the record entirely. DELETE without a WHERE clause would erase the entire city\'s history. The WHERE clause is the difference between justice and catastrophe.',
    npcName: 'The Head Scribe',
    npcLine: '11 rows deleted — counterfeits removed.',
    terminalOutput: [
      'DELETE 11',
      '✓ 11 counterfeit artifacts permanently removed.',
    ],
    terminalOutputError: "Try: DELETE FROM artifacts WHERE condition = 'counterfeit'",
    xp: 55,
    unlocksCodex: true,
    codexKey: 'sql-delete',
    hint: "Delete specific rows: DELETE FROM artifacts WHERE condition = 'counterfeit'",
    stateChange: { mutates: true },
    specialType: null,
  },

  // ─── LEVEL 9: The Deep Vaults ────────────────────────────────────────────
  {
    id: 'sql-mission-42',
    level: 9,
    command: 'SELECT DISTINCT era FROM artifacts',
    aliases: ['select distinct era from artifacts'],
    narrative: 'How many unique eras are actually represented in the record? DISTINCT collapses duplicates — instead of 2,847 era values, you get one row per unique era. Eight distinct eras surface.',
    npcName: 'The Deep Keeper',
    npcLine: '8 unique eras — the city\'s full historical span.',
    terminalOutput: [
      'era',
      '-----------',
      'Bronze Age',
      'Iron Age',
      'Classical',
      'Hellenistic',
      'Late Period',
      'Neolithic',
      'Modern',
      'Unknown',
      '',
      '(8 rows)',
    ],
    terminalOutputError: 'Try: SELECT DISTINCT era FROM artifacts',
    xp: 40,
    unlocksCodex: true,
    codexKey: 'sql-distinct',
    hint: 'Remove duplicates: SELECT DISTINCT era FROM artifacts',
    stateChange: {},
    specialType: null,
  },
  {
    id: 'sql-mission-43',
    level: 9,
    command: 'SELECT name FROM artifacts WHERE age > (SELECT AVG(age) FROM artifacts)',
    aliases: ['select name from artifacts where age > (select avg(age) from artifacts)'],
    narrative: 'You want artifacts older than average — but you don\'t know the average yet. A subquery calculates it first, in the inner parentheses, and passes the result to the outer query as if it were a hardcoded number. The query answers its own prerequisite.',
    npcName: 'The Deep Keeper',
    npcLine: '1,203 rows — artifacts older than the 1,847-year average.',
    terminalOutput: [
      'name',
      '--------------------',
      'Bronze Dagger',
      'Obsidian Mirror',
      'Stone Altar',
      '...',
      '',
      '(1,203 rows — older than avg 1,847 years)',
    ],
    terminalOutputError: 'Try: SELECT name FROM artifacts WHERE age > (SELECT AVG(age) FROM artifacts)',
    xp: 55,
    unlocksCodex: true,
    codexKey: 'sql-subquery',
    hint: 'Nest a query inside another: WHERE age > (SELECT AVG(age) FROM artifacts)',
    stateChange: {},
    specialType: null,
  },
  {
    id: 'sql-mission-44',
    level: 9,
    command: 'SELECT name FROM excavators WHERE id IN (SELECT DISTINCT excavator_id FROM artifacts WHERE era = \'Bronze Age\')',
    aliases: [
      "select name from excavators where id in (select distinct excavator_id from artifacts where era = 'bronze age')",
      'select name from excavators where id in (select distinct excavator_id from artifacts where era = \'Bronze Age\')',
    ],
    narrative: 'Which excavators worked Bronze Age sites? The inner query pulls the IDs; the outer query translates IDs to names. IN checks membership in the subquery\'s result — a lookup across two tables without an explicit JOIN.',
    npcName: 'The Deep Keeper',
    npcLine: '8 excavators worked Bronze Age sites.',
    terminalOutput: [
      'name',
      '-------------------',
      'Maris Theron',
      'Petra Voss',
      'Dex Calloway',
      'Rafi Sanz',
      '...',
      '',
      '(8 rows)',
    ],
    terminalOutputError: "Try: SELECT name FROM excavators WHERE id IN (SELECT DISTINCT excavator_id FROM artifacts WHERE era = 'Bronze Age')",
    xp: 55,
    unlocksCodex: false,
    codexKey: 'sql-subquery',
    hint: "Use IN with a subquery: WHERE id IN (SELECT DISTINCT excavator_id FROM artifacts WHERE era = 'Bronze Age')",
    stateChange: {},
    specialType: null,
  },
  {
    id: 'sql-mission-45',
    level: 9,
    command: "SELECT name, age, CASE WHEN age > 5000 THEN 'Ancient' WHEN age > 2000 THEN 'Old' WHEN age > 500 THEN 'Medieval' ELSE 'Recent' END AS classification FROM artifacts",
    aliases: ["select name, age, case when age > 5000 then 'ancient' when age > 2000 then 'old' when age > 500 then 'medieval' else 'recent' end as classification from artifacts"],
    narrative: 'The museum needs labels for display cases. CASE WHEN is a conditional column — it reads each row\'s age and assigns a human-readable classification. The database becomes a curator.',
    npcName: 'The Deep Keeper',
    npcLine: 'Every artifact labeled: Ancient / Old / Medieval / Recent.',
    terminalOutput: [
      'name              | age  | classification',
      '------------------|------|---------------',
      'Stone Altar       | 7200 | Ancient',
      'Obsidian Mirror   | 4100 | Old',
      'Bronze Dagger     | 3200 | Old',
      'Clay Vessel       | 1847 | Old',
      'Iron Lance        | 890  | Medieval',
      'Modern Replica    | 12   | Recent',
      '...',
    ],
    terminalOutputError: "Try: SELECT name, age, CASE WHEN age > 5000 THEN 'Ancient' WHEN age > 2000 THEN 'Old' WHEN age > 500 THEN 'Medieval' ELSE 'Recent' END AS classification FROM artifacts",
    xp: 60,
    unlocksCodex: true,
    codexKey: 'sql-case',
    hint: "Use CASE WHEN for conditional columns: CASE WHEN age > 5000 THEN 'Ancient' ... END AS classification",
    stateChange: {},
    specialType: null,
  },
  {
    id: 'sql-mission-46',
    level: 9,
    command: "SELECT era, COUNT(*) AS artifact_count, CASE WHEN COUNT(*) > 500 THEN 'Major Era' WHEN COUNT(*) > 100 THEN 'Notable Era' ELSE 'Minor Era' END AS significance FROM artifacts GROUP BY era",
    aliases: ["select era, count(*) as artifact_count, case when count(*) > 500 then 'major era' when count(*) > 100 then 'notable era' else 'minor era' end as significance from artifacts group by era"],
    narrative: 'Combine GROUP BY with CASE — every era gets a count and a significance label. The city\'s historical weight is now quantified and categorized in a single query.',
    npcName: 'The Deep Keeper',
    npcLine: '8 eras classified by artifact density.',
    terminalOutput: [
      'era          | artifact_count | significance',
      '-------------|----------------|-------------',
      'Classical    | 891            | Major Era',
      'Late Period  | 789            | Major Era',
      'Bronze Age   | 341            | Notable Era',
      'Iron Age     | 257            | Notable Era',
      'Modern       | 146            | Notable Era',
      'Neolithic    | 89             | Minor Era',
      '...',
    ],
    terminalOutputError: "Try: SELECT era, COUNT(*) AS artifact_count, CASE WHEN COUNT(*) > 500 THEN 'Major Era' WHEN COUNT(*) > 100 THEN 'Notable Era' ELSE 'Minor Era' END AS significance FROM artifacts GROUP BY era",
    xp: 60,
    unlocksCodex: false,
    codexKey: 'sql-case',
    hint: "Combine GROUP BY with CASE WHEN: CASE WHEN COUNT(*) > 500 THEN 'Major Era' ... END",
    stateChange: {},
    specialType: null,
  },

  // ─── LEVEL 10: The Grand Archive ────────────────────────────────────────
  {
    id: 'sql-mission-47',
    level: 10,
    command: 'SELECT era, excavator_id, COUNT(*) AS finds, ROW_NUMBER() OVER (PARTITION BY era ORDER BY COUNT(*) DESC) AS rank FROM artifacts GROUP BY era, excavator_id',
    aliases: ['select era, excavator_id, count(*) as finds, row_number() over (partition by era order by count(*) desc) as rank from artifacts group by era, excavator_id'],
    narrative: 'A window opens across the data — a special kind of function that can see beyond the current row. ROW_NUMBER() assigns each excavator a sequential position within their era based on find count, without collapsing the rows.',
    npcName: 'The Grand Archivist',
    npcLine: 'Rankings revealed — top excavators per era identified.',
    terminalOutput: [
      'era          | excavator_id | finds | rank',
      '-------------|--------------|-------|-----',
      'Bronze Age   | 7            | 214   | 1',
      'Bronze Age   | 3            | 89    | 2',
      'Bronze Age   | 12           | 38    | 3',
      'Classical    | 1            | 301   | 1',
      'Classical    | 5            | 187   | 2',
      '...',
      '',
      '(pre-computed result — window functions)',
    ],
    terminalOutputError: 'Try: SELECT era, excavator_id, COUNT(*) AS finds, ROW_NUMBER() OVER (PARTITION BY era ORDER BY COUNT(*) DESC) AS rank FROM artifacts GROUP BY era, excavator_id',
    xp: 70,
    unlocksCodex: true,
    codexKey: 'sql-window',
    hint: 'Use ROW_NUMBER() OVER (PARTITION BY era ORDER BY COUNT(*) DESC)',
    stateChange: {},
    specialType: 'precomputed',
  },
  {
    id: 'sql-mission-48',
    level: 10,
    command: "WITH bronze_age AS (SELECT * FROM artifacts WHERE era = 'Bronze Age') SELECT name, age FROM bronze_age WHERE age > 4000",
    aliases: ["with bronze_age as (select * from artifacts where era = 'bronze age') select name, age from bronze_age where age > 4000"],
    narrative: 'A CTE — a Common Table Expression — names a subquery so you can reference it cleanly. bronze_age becomes a temporary named result, readable and reusable within this query. You\'re not just querying; you\'re building structured thought.',
    npcName: 'The Grand Archivist',
    npcLine: 'CTE defined — 14 ancient Bronze Age artifacts isolated.',
    terminalOutput: [
      'name              | age',
      '------------------|-----',
      'Obsidian Mirror   | 4100',
      'Bronze Idol       | 4800',
      'Sacred Vessel     | 5200',
      '...',
      '',
      '(14 rows — Bronze Age artifacts older than 4,000 years)',
    ],
    terminalOutputError: "Try: WITH bronze_age AS (SELECT * FROM artifacts WHERE era = 'Bronze Age') SELECT name, age FROM bronze_age WHERE age > 4000",
    xp: 65,
    unlocksCodex: true,
    codexKey: 'sql-cte',
    hint: "Define a CTE with WITH: WITH bronze_age AS (SELECT * FROM artifacts WHERE era = 'Bronze Age')",
    stateChange: {},
    specialType: 'precomputed',
  },
  {
    id: 'sql-mission-49',
    level: 10,
    command: "WITH maris AS (SELECT id FROM excavators WHERE name = 'Maris Theron') SELECT a.name, a.era, a.age FROM artifacts a WHERE a.excavator_id IN (SELECT id FROM maris) ORDER BY a.era, a.age DESC",
    aliases: ["with maris as (select id from excavators where name = 'maris theron') select a.name, a.era, a.age from artifacts a where a.excavator_id in (select id from maris) order by a.era, a.age desc"],
    narrative: 'A CTE identifies Maris Theron by name, then the main query uses that ID to pull her complete artifact history — sorted by era and age. The Grand Archive hums as centuries of data align into an accusation.',
    npcName: 'The Grand Archivist',
    npcLine: 'Full artifact history for Maris Theron — pattern confirmed across all eras.',
    terminalOutput: [
      'name                | era        | age',
      '--------------------|------------|-----',
      'Bronze Idol         | Bronze Age | 4800',
      'Clay Tablet Alpha   | Bronze Age | 3400',
      '...',
      'Iron Dagger         | Iron Age   | 2800',
      '...',
      '',
      '(847 rows — all eras, oldest first within each)',
    ],
    terminalOutputError: "Try: WITH maris AS (SELECT id FROM excavators WHERE name = 'Maris Theron') SELECT a.name, a.era, a.age FROM artifacts a WHERE a.excavator_id IN (SELECT id FROM maris) ORDER BY a.era, a.age DESC",
    xp: 65,
    unlocksCodex: false,
    codexKey: 'sql-cte',
    hint: "Name your CTE: WITH maris AS (SELECT id FROM excavators WHERE name = 'Maris Theron')",
    stateChange: {},
    specialType: 'precomputed',
  },
  {
    id: 'sql-mission-50',
    level: 10,
    command: "CREATE VIEW pristine_bronze AS SELECT name, age, site_id FROM artifacts WHERE era = 'Bronze Age' AND condition = 'pristine'",
    aliases: ["create view pristine_bronze as select name, age, site_id from artifacts where era = 'bronze age' and condition = 'pristine'"],
    narrative: 'You create a VIEW — a named, saved query that behaves like a permanent table but holds no data itself. It\'s a window, not a wall. Future archaeologists can query pristine_bronze without knowing the underlying complexity.',
    npcName: 'The Grand Archivist',
    npcLine: "View 'pristine_bronze' created — reusable query stored.",
    terminalOutput: [
      'CREATE VIEW',
      "✓ View 'pristine_bronze' created successfully.",
    ],
    terminalOutputError: "Try: CREATE VIEW pristine_bronze AS SELECT name, age, site_id FROM artifacts WHERE era = 'Bronze Age' AND condition = 'pristine'",
    xp: 60,
    unlocksCodex: true,
    codexKey: 'sql-view',
    hint: "Create a view: CREATE VIEW pristine_bronze AS SELECT ... FROM artifacts WHERE era = 'Bronze Age' AND condition = 'pristine'",
    stateChange: { createsView: 'pristine_bronze' },
    specialType: null,
  },
  {
    id: 'sql-mission-51',
    level: 10,
    command: 'SELECT * FROM pristine_bronze ORDER BY age DESC',
    aliases: ['select * from pristine_bronze order by age desc'],
    narrative: 'You query your own view like a table. The abstraction holds. Cleanly, the fourteen most pristine Bronze Age artifacts surface — sorted oldest first. One catches your eye: The Codex of Queryra, age 9,247 years, site 3.',
    npcName: 'The Grand Archivist',
    npcLine: 'The Codex of Queryra — oldest pristine Bronze Age artifact.',
    terminalOutput: [
      'name                  | age  | site_id',
      '----------------------|------|--------',
      'The Codex of Queryra  | 9247 | 3',
      'Ancient Figurine      | 6800 | 3',
      'Sacred Vessel         | 5200 | 1',
      '...',
      '',
      '(14 rows)',
    ],
    terminalOutputError: 'Try: SELECT * FROM pristine_bronze ORDER BY age DESC',
    xp: 50,
    unlocksCodex: false,
    codexKey: 'sql-view',
    hint: 'Query a view like a table: SELECT * FROM pristine_bronze ORDER BY age DESC',
    stateChange: {},
    specialType: null,
  },
  {
    id: 'sql-mission-52',
    level: 10,
    command: "SELECT a.name, s.location, s.depth FROM artifacts a JOIN sites s ON a.site_id = s.id WHERE a.name = 'The Codex of Queryra'",
    aliases: ["select a.name, s.location, s.depth from artifacts a join sites s on a.site_id = s.id where a.name = 'the codex of queryra'"],
    narrative: 'You need its exact location. A targeted JOIN between artifacts and sites for this single row. The coordinates return: Site 3, Grid NW-7, depth 42 meters. The deepest point of the entire excavation.',
    npcName: 'The Grand Archivist',
    npcLine: 'Location confirmed — Site 3, NW-7, 42m depth.',
    terminalOutput: [
      'name                  | location | depth',
      '----------------------|----------|------',
      'The Codex of Queryra  | NW-7     | 42',
      '',
      '(1 row)',
    ],
    terminalOutputError: "Try: SELECT a.name, s.location, s.depth FROM artifacts a JOIN sites s ON a.site_id = s.id WHERE a.name = 'The Codex of Queryra'",
    xp: 55,
    unlocksCodex: false,
    codexKey: 'sql-join',
    hint: "JOIN artifacts to sites and filter: WHERE a.name = 'The Codex of Queryra'",
    stateChange: {},
    specialType: null,
  },
  {
    id: 'sql-mission-53',
    level: 10,
    command: "SELECT message FROM codex WHERE seal = 'unbroken' ORDER BY inscription_order",
    aliases: ["select message from codex where seal = 'unbroken' order by inscription_order"],
    narrative: 'The Codex of Queryra is not an artifact — it is a database. Its final table holds a message, inscribed in order, sealed for nine millennia. Your query returns it row by row.',
    npcName: 'The Grand Archivist',
    npcLine: 'Query complete — 1 message returned. The city has spoken.',
    terminalOutput: [
      '"We did not perish from war or flood."',
      '"We perished because we stopped asking questions of our own records."',
      '"The data was always there."',
      '"No one queried it."',
    ],
    terminalOutputError: "Try: SELECT message FROM codex WHERE seal = 'unbroken' ORDER BY inscription_order",
    xp: 100,
    unlocksCodex: false,
    codexKey: null,
    hint: "Query the codex table: SELECT message FROM codex WHERE seal = 'unbroken' ORDER BY inscription_order",
    stateChange: {},
    specialType: 'dramatic',
  },
]
